---
title: "DharmaResearch "
output: 
    flexdashboard::flex_dashboard:
        #logo: logo_H.jpg
        orientation: rows
        #vertical_layout: scroll
        runtime: shiny
---

```{r}

#### init directories and knitr ####
library("knitr")
workingDir <- normalizePath("../../")
opts_knit$set(root.dir= workingDir)
setwd(workingDir)


#### Init ####
library(flexdashboard)
library(plotly)
library(fmsb)
library(data.table)
library(quantmod)
library(ggplot2)
library(RcppRoll)


#### load datas ####
load("Data/indicators.RData")
load("Data/histoPrices.RData")
load("Data/securities.RData")
load("Data/strats.RData")


#### source functions ####
source("R/Source/plotRadar.R")
source("R/Source/getLogReturn.R")
source("R/Source/getReturnPlot.R")
source("R/Source/getDatabase.R")
source("R/Source/computeFundFields.R")
source("R/Source/computeDailyFields.R")
source("R/Source/changeInftoNA.R")
source("R/Source/reorderColumns.R")
source("R/Source/perfTable.R")
source("R/Source/getStyle.R")


#### get requested datas ####
database <- getDatabase(histoPrices, indicators, securities)

valueFields  <- scan("Config/valueStyleFields.txt",  what= "character") 
growthFields <- scan("Config/growthStyleFields.txt", what= "character")

```


Single Security View
=======================================================================


Column {.sidebar data-width=350}
-----------------------------------------------------------------------


Choose security to be displayed

```{r}

#### set input boxes ####
selectInput("secName", 
            label = NULL,
            choices = (unique(database$Short_Name)),
            selected = "APPLE INC")

radioButtons("button", 
             label= NULL,
             c("Ranking"= "Ranking",
               "Rating" = "Rating"),
             inline= TRUE)

checkboxInput("absolute", label = "absolute", value= FALSE)


#### set reactive variables ####
tic   <- reactive(unique(database[Short_Name == input$secName, Ticker]))
radar <- reactive(plotRadar(tic(), database, strats))
table <- reactive(perfTable(tic(), strats, database, input))

```

Price Return
```{r}

#### render histo perf table ####
renderTable({
    
    table()

    }, bordered = "xs")

#### plot radar chart ####
renderPlot({
    
    radar()

    })

```

Row {data-height=150}
-----------------------------------------------------------------------

### Univer Ranking
```{r}

#### render Gauges ####
renderGauge({
    
    gauge(round(strats$lastScoring[Ticker == tic(), Ranking] * 100, 2),
          min = 0, max = 100, symbol = '%',
          gaugeSectors(success= c(60, 100),
                       warning= c(40,  60),
                       danger=  c( 0,  40)))

    })

```

### GICS Sector Ranking
```{r}

# render Gauges
renderGauge({
    
    gauge(round(strats$lastScoring[Ticker == tic(), RankingGics] * 100, 2),
          min = 0, max = 100, symbol = '%',
          gaugeSectors(success= c(60, 100),
                       warning= c(40,  60),
                       danger=  c( 0,  40)))
    
    })

```


### Rating
```{r}

renderValueBox({    
    
    valueBox(value=   last(strats$rating[Ticker == tic(), Rating]), 
             icon=    "fa-star",
             color=   ifelse(last(strats$rating[Ticker == tic(), Rating]) %in% c(2, 3, 4),
                             "success", "warning"))
    
    })

```

### Grade
```{r}

renderValueBox({    
    
    valueBox(value=   last(strats$grade[Ticker == tic(), Grade]), 
             icon=    "fa-graduation-cap",
             color=   "primary")
    
    })

```

### Value Style
```{r}

# render Gauges
renderGauge({
    
    gauge(round(last(getStyle(database[Ticker== tic(),], valueFields, growthFields)$Value) * 100, 2),
          min = 0, max = 100, symbol = '%',
          gaugeSectors(success= c(70, 100),
                       warning= c(30,  70),
                       danger=  c( 0,  30)))
    
    })

```

### Growth Style
```{r}

# render Gauges
renderGauge({
    
    gauge(round(last(getStyle(database[Ticker== tic(),], valueFields, growthFields)$Growth) * 100, 2),
          min = 0, max = 100, symbol = '%',
          gaugeSectors(success= c(70, 100),
                       warning= c(30,  70),
                       danger=  c( 0,  30)))
    
    })

```


Row {data-height=800}
-----------------------------------------------------------------------

### histo price

```{r}

#plot histo chart
renderPlotly({
    
    dat <- database[Short_Name == input$secName, .(Date, Adj_Px_Last)]
    
    dat[, ':=' (Rsi5=   RSI(Adj_Px_Last, n=5,  maType="EMA", wilder=TRUE),
                Rsi9=   RSI(Adj_Px_Last, n=9,  maType="EMA", wilder=TRUE),
                Rsi14=  RSI(Adj_Px_Last, n=14, maType="EMA", wilder=TRUE),
                Rsi20=  RSI(Adj_Px_Last, n=20, maType="EMA", wilder=TRUE))]
    
    p6 <-  # plot line & smooth Adj_Px_Last
        ggplot(dat, aes(Date, Adj_Px_Last)) +
        geom_line() +
        geom_smooth()
    
    p7.1 <-  # Plot RSI 5/9/14/20
        ggplot(data= dat, mapping=aes(x=Date, y=Rsi20)) +
        geom_line() + geom_smooth() +
        geom_hline(aes(yintercept= quantile(Rsi20, 0.9, na.rm= TRUE)), colour="orangered3", size=0.2) +
        geom_ribbon(aes(ymin= quantile(Rsi20, 0.9, na.rm= TRUE),
                        ymax= ifelse(Rsi20 > quantile(Rsi20, 0.9, na.rm= TRUE),
                                     Rsi20,
                                     quantile(Rsi20, 0.9, na.rm= TRUE))),
                    fill="orangered3") +
        geom_hline(aes(yintercept= quantile(Rsi20, 0.1, na.rm= TRUE)), colour="green3", size=0.2) +
        geom_ribbon(aes(ymin= ifelse(Rsi20 < quantile(Rsi20, 0.1, na.rm= TRUE),
                                     Rsi20,
                                     quantile(Rsi20, 0.1, na.rm= TRUE)),
                        ymax= quantile(Rsi20, 0.1, na.rm= TRUE)),
                    fill="green3") +
        labs(y="Rsi 20")
    
    p7.2 <-  # Plot RSI 5/9/14/20
        ggplot(data= dat, mapping=aes(x=Date, y=Rsi5)) +
        geom_line() + geom_smooth() +
        geom_hline(aes(yintercept= quantile(Rsi5, 0.9, na.rm= TRUE)), colour="orangered3", size=0.2) +
        geom_ribbon(aes(ymin= quantile(Rsi5, 0.9, na.rm= TRUE),
                        ymax= ifelse(Rsi5 > quantile(Rsi5, 0.9, na.rm= TRUE),
                                     Rsi5,
                                     quantile(Rsi5, 0.9, na.rm= TRUE))),
                    fill="orangered3") +
        geom_hline(aes(yintercept= quantile(Rsi5, 0.1, na.rm= TRUE)), colour="green3", size=0.2) +
        geom_ribbon(aes(ymin= ifelse(Rsi5 < quantile(Rsi5, 0.1, na.rm= TRUE),
                                     Rsi5,
                                     quantile(Rsi5, 0.1, na.rm= TRUE)),
                        ymax= quantile(Rsi5, 0.1, na.rm= TRUE)),
                    fill="green3") +
        labs(y="Rsi 5")
    
    subplot(p6, p7.1, p7.2, nrows=3, shareX= TRUE, heights= c(0.7, 0.15, 0.15))
    
    })

```


Row {data-height=250}
-----------------------------------------------------------------------

### rating

```{r}

renderPlotly({
    
    res <- strats$rating[Ticker == tic()][strats$grade[Ticker == tic()]]
    
    ggplot(res) + aes(x= Date) +
        geom_line(aes(y= Rating, color="rating")) +
        geom_line(aes(y= Grade,  color="grade")) +
        aes(ylab= "Rating", ymin= 1, ymax= max(Rating)) +
        scale_y_reverse(breaks= 1:7, name="Rating") +
        theme(legend.position= c(.8, 0.3))
    
    })

```

### ranking

```{r}

renderPlotly({
    
    res <- strats$scoring[Ticker== tic(), 
                           .(Date, Ticker, Ranking, RankingGics)]
    
    ggplot(res, aes(x=Date)) +
        geom_line(aes(y=Ranking, colour="univer")) +
        geom_line(aes(y=RankingGics, colour="sector")) +
        aes(ylab= "Ranking",
            ymin= min(floor(min(RankingGics)   / 0.05) * 0.05,
                      floor(min(Ranking)       / 0.05) * 0.05),
            ymax= max(ceiling(max(RankingGics) / 0.05) * 0.05,
                      ceiling(max(Ranking)     / 0.05) * 0.05)) + 
        theme(legend.position= c(.8, 0.3))
    
    })

```



Style
=======================================================================


Column {data-height=500}
-----------------------------------------------------------------------

### Price Return

```{r}
#plot histo chart

renderPlotly({
    # plot line & smooth Adj_Px_Last
    dat <- database[Short_Name == input$secName, .(Date, Adj_Px_Last)]
    
    ggplot(dat, aes(Date, Adj_Px_Last)) +
    geom_line() +
    geom_smooth()
    
    })

```


Column data-height=500}
-----------------------------------------------------------------------

### Style

```{r}

renderPlotly({
    # plot growth/value style
    res <- getStyle(database[Ticker== tic()], valueFields, growthFields)
    
    ggplot(res, aes(x=Date)) +
        geom_line(aes(y=Value,  colour="value")) +
        geom_line(aes(y=Growth, colour="growth")) +
         aes(ylab= "Style",
             ymin= 0,
             ymax= 1)

})

```

### Momentum

```{r}

renderPlotly({
    # plot growth/value style
    res <- getStyle(database[Ticker== tic()], valueFields, growthFields)
    
    ggplot(res, aes(Date, Momentum)) +
        geom_line() +
        geom_smooth()
    
})

```



Other Page
=======================================================================

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

renderPlot({
    
    getReturnPlot(dat = getLogReturn(strats$rating, database), dt = "2012-01-31", field = "Rating")
    
    })

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

renderPlot({
    
    getReturnPlot(getLogReturn(strats$scoring, database), "2012-01-31", "Ranking")
    
    })

```

### Chart C


